CREATE TABLE epoch_param (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    epoch_no INT UNSIGNED NOT NULL,
    min_fee_a INT UNSIGNED,
    min_fee_b INT UNSIGNED,
    max_block_size INT UNSIGNED,
    max_tx_size INT UNSIGNED,
    max_bh_size INT UNSIGNED,
    key_deposit BIGINT UNSIGNED,
    pool_deposit BIGINT UNSIGNED,
    max_epoch INT UNSIGNED,
    optimal_pool_count INT UNSIGNED,
    influence DOUBLE,
    monetary_expand_rate DOUBLE,
    treasury_growth_rate DOUBLE,
    decentralisation DOUBLE,
    extra_entropy VARBINARY(32),
    protocol_major INT UNSIGNED,
    protocol_minor INT UNSIGNED,
    min_utxo_value BIGINT UNSIGNED,
    min_pool_cost BIGINT UNSIGNED,
    nonce VARBINARY(32),
    coins_per_utxo_size BIGINT UNSIGNED,
    cost_model_id BIGINT,
    price_mem DOUBLE,
    price_step DOUBLE,
    max_tx_ex_mem BIGINT UNSIGNED,
    max_tx_ex_steps BIGINT UNSIGNED,
    max_block_ex_mem BIGINT UNSIGNED,
    max_block_ex_steps BIGINT UNSIGNED,
    max_val_size BIGINT UNSIGNED,
    collateral_percent INT UNSIGNED,
    max_collateral_inputs INT UNSIGNED,
    pvt_motion_no_confidence DOUBLE,
    pvt_committee_normal DOUBLE,
    pvt_committee_no_confidence DOUBLE,
    pvt_hard_fork_initiation DOUBLE,
    pvtpp_security_group DOUBLE,
    dvt_motion_no_confidence DOUBLE,
    dvt_committee_normal DOUBLE,
    dvt_committee_no_confidence DOUBLE,
    dvt_update_to_constitution DOUBLE,
    dvt_hard_fork_initiation DOUBLE,
    dvt_p_p_network_group DOUBLE,
    dvt_p_p_economic_group DOUBLE,
    dvt_p_p_technical_group DOUBLE,
    dvt_p_p_gov_group DOUBLE,
    dvt_treasury_withdrawal DOUBLE,
    committee_min_size BIGINT UNSIGNED,
    committee_max_term_length BIGINT UNSIGNED,
    gov_action_lifetime BIGINT UNSIGNED,
    gov_action_deposit BIGINT UNSIGNED,
    drep_deposit BIGINT UNSIGNED,
    drep_activity BIGINT UNSIGNED,
    min_fee_ref_script_cost_per_byte DOUBLE,
    block_id BIGINT NOT NULL,
    FOREIGN KEY (cost_model_id) REFERENCES cost_model (id),
    FOREIGN KEY (block_id) REFERENCES block (id)
);
